# --- Étape 1 : Construction (Builder) ---
FROM node:24 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx svelte-kit sync
RUN npm run build

# --- Étape 2 : Exécution (Runner) ---
FROM node:24 AS runner
WORKDIR /app

# On ne copie que le build et les dépendances nécessaires
COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

# Install serve to serve the static files
RUN npm install -g serve

# Railway et les autres injectent dynamiquement le PORT
ENV NODE_ENV=production
ENV PORT=5173
EXPOSE 5173

# Serve the static files from the build directory
CMD ["serve", "-s", "build", "-l", "5173"]