volumes:
  skillfusion_volume:

networks:
  skillfusion_network:

services:
  db:
    image: postgres:18
    container_name: skillfusion_db
    environment:
      POSTGRES_USER: usersf
      POSTGRES_PASSWORD: usersf
      POSTGRES_DB: usersf
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    networks:
      - skillfusion_network

  api:
    build: ./api
    container_name: skillfusion_api
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - skillfusion_network
    command: npm run dev

  client:
    build: ./client
    container_name: skillfusion_client
    ports:
      - "5173:5173"
    depends_on:
      - api
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - skillfusion_network
    command: npm run dev -- --host