
@BASE_URL=http://localhost:3000

### cours active
GET {{BASE_URL}}/api/cours-active
Content-Type: application/json

### cours active avec id
GET {{BASE_URL}}/api/cours-active/1
Content-Type: application/json

### creer une cours active
POST {{BASE_URL}}/api/cours-active
Content-Type: application/json

{
    "userId": 1,
    "coursId": 1,
    "IsEnd": false
}



### modifier une cours active
PATCH {{BASE_URL}}/api/cours-active/1
Content-Type: application/json

{
    "title": "Cours de charpente",
    "description": "Apprenez les bases de la charpente avec ce cours complet.",
    "categoryId": 1,
    "instructorId": 1,
    "isActive": true
}

### supprimer une cours active
DELETE {{BASE_URL}}/api/cours-active/3
Content-Type: application/json
