import type { Prisma } from '../../../prisma/generated';

export const commentsData: Prisma.CommentCreateManyInput[] = [
    {
        description: "Quelle épaisseur d'étagère recommandez-vous ?",
        authorId: 2,
        coursId: 1,
    },
    { description: 'Le kit comprend-il toutes les vis ?', authorId: 3, coursId: 2 },
    { description: 'Quel lubrifiant utiliser pour les gonds ?', authorId: 6, coursId: 3 },
    { description: 'Faut-il une sous-couche pour le parquet ?', authorId: 7, coursId: 4 },
    { description: 'Quel bois choisir pour la boîte ?', authorId: 9, coursId: 5 },
    {
        description: 'Comment éviter les odeurs après changement ?',
        authorId: 2,
        coursId: 6,
    },
    { description: 'Quelle taille de joint pour la réparation ?', authorId: 3, coursId: 7 },
    { description: 'Le WC suspendu supporte-t-il le poids ?', authorId: 6, coursId: 8 },
    { description: 'Quel type de robinet pour douche ?', authorId: 7, coursId: 9 },
    { description: 'Comment étanchéifier le receveur ?', authorId: 9, coursId: 10 },
    { description: 'Faut-il un disjoncteur différentiel ?', authorId: 2, coursId: 11 },
    { description: 'Quelle section de câble pour la prise ?', authorId: 3, coursId: 12 },
    { description: "Comment identifier l'ampérage du fusible ?", authorId: 6, coursId: 13 },
    { description: "Quelle puissance d'ampoule recommandée ?", authorId: 7, coursId: 14 },
    { description: 'Le détecteur est-il connecté au réseau ?', authorId: 9, coursId: 15 },
    { description: 'À quelle fréquence purger les radiateurs ?', authorId: 2, coursId: 16 },
    { description: 'Quel type de radiateur choisir ?', authorId: 3, coursId: 17 },
    {
        description: 'Faut-il un professionnel pour la cheminée ?',
        authorId: 6,
        coursId: 18,
    },
    {
        description: 'Le thermostat est-il compatible avec mon système ?',
        authorId: 7,
        coursId: 19,
    },
    { description: 'Quel isolant pour un mur humide ?', authorId: 9, coursId: 20 },
    {
        description: 'Comment aligner les faïences parfaitement ?',
        authorId: 2,
        coursId: 21,
    },
    { description: 'Quelle épaisseur de mortier pour le sol ?', authorId: 3, coursId: 22 },
    { description: 'Le mastic sèche-t-il rapidement ?', authorId: 6, coursId: 23 },
    { description: 'Comment fixer la moquette sans colle ?', authorId: 7, coursId: 24 },
    { description: 'Faut-il reboucher derrière le carreau ?', authorId: 9, coursId: 25 },
    { description: 'Quelle peinture pour un mur extérieur ?', authorId: 2, coursId: 26 },
    { description: "Comment enlever l'ancien papier peint ?", authorId: 3, coursId: 27 },
    { description: 'Quelle peinture pour boiseries ?', authorId: 6, coursId: 28 },
    { description: 'Où trouver des peintures décoratives ?', authorId: 7, coursId: 29 },
    { description: 'Comment éviter les coulures au plafond ?', authorId: 9, coursId: 30 },
];
