import type { Prisma } from '../../../prisma/generated';

export const coursesData: Prisma.CoursCreateManyInput[] = [
    // Menuiserie (5 cours)
    {
        title: 'Poser une étagère murale en bois',
        slug: 'poser-une-etagere-murale-en-bois',
        littleSummary: 'Apprenez à fixer une étagère droite, stable et adaptée à votre mur.',
        summary:
            "Ce cours vous guide du choix des matériaux à la fixation finale d'une étagère murale. Vous verrez comment mesurer, percer, choisir des chevilles adaptées et fixer le support de manière propre.",
        difficulty: 2,
        authorId: 4,
        categoryId: 1,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Assembler une étagère en kit',
        slug: 'assembler-une-etagere-en-kit',
        littleSummary: 'Montez facilement une étagère pré-découpée.',
        summary:
            'Ce tutoriel montre comment assembler une étagère en kit avec des vis et des chevilles, en respectant les instructions pour une stabilité parfaite.',
        difficulty: 1,
        authorId: 4,
        categoryId: 1,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Réparer une porte qui grince',
        slug: 'reparer-une-porte-qui-grince',
        littleSummary: 'Éliminez les grincements de porte en quelques gestes.',
        summary:
            'Découvrez comment identifier la cause du grincement et appliquer la solution appropriée, comme lubrifier les gonds ou ajuster la porte.',
        difficulty: 2,
        authorId: 4,
        categoryId: 1,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Poser du parquet flottant',
        slug: 'poser-du-parquet-flottant',
        littleSummary: 'Installez un parquet sans colle ni clous.',
        summary:
            "Apprenez à poser un parquet flottant sur un sol préparé, en veillant à l'expansion et à l'alignement pour un résultat professionnel.",
        difficulty: 3,
        authorId: 4,
        categoryId: 1,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Fabriquer une boîte de rangement',
        slug: 'fabriquer-une-boite-de-rangement',
        littleSummary: 'Créez votre propre boîte en bois pour organiser.',
        summary:
            "Ce cours enseigne la découpe, l'assemblage et la finition d'une boîte de rangement simple, idéale pour débutants en menuiserie.",
        difficulty: 3,
        authorId: 4,
        categoryId: 1,
        numberPage: 4,
        visibility: true,
    },
    // Plomberie (5 cours)
    {
        title: 'Installer un siphon de lavabo',
        slug: 'installer-un-siphon-de-lavabo',
        littleSummary: "Remplacez un siphon en évitant les fuites et en respectant l'écoulement.",
        summary:
            "Ce cours de plomberie détaille la dépose de l'ancien siphon, le choix du bon modèle et le montage correct des joints pour une installation durable sans odeurs ni fuites.",
        difficulty: 3,
        authorId: 5,
        categoryId: 2,
        numberPage: 4,
        visibility: true,
    },
    {
        title: "Réparer une fuite d'eau",
        slug: 'reparer-une-fuite-d-eau',
        littleSummary: 'Stoppez une fuite rapidement et efficacement.',
        summary:
            "Identifiez le type de fuite, coupez l'eau et appliquez la réparation appropriée, comme changer un joint ou resserrer un raccord.",
        difficulty: 2,
        authorId: 5,
        categoryId: 2,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Installer un WC suspendu',
        slug: 'installer-un-wc-suspendu',
        littleSummary: 'Montez un WC moderne et design.',
        summary:
            "Ce guide explique l'installation d'un WC suspendu, de la fixation de la plaque au raccordement des eaux, en toute sécurité.",
        difficulty: 4,
        authorId: 5,
        categoryId: 2,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Changer un robinet de douche',
        slug: 'changer-un-robinet-de-douche',
        littleSummary: 'Remplacez votre robinet de douche usé.',
        summary:
            "Apprenez à démonter l'ancien robinet, choisir le nouveau modèle et le raccorder correctement pour une douche fonctionnelle.",
        difficulty: 3,
        authorId: 5,
        categoryId: 2,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Installer une douche',
        slug: 'installer-une-douche',
        littleSummary: 'Posez une douche complète dans votre salle de bain.',
        summary:
            "De la préparation du sol à l'installation du receveur, ce cours couvre tous les aspects pour une douche étanche et pratique.",
        difficulty: 4,
        authorId: 5,
        categoryId: 2,
        numberPage: 4,
        visibility: true,
    },
    // Electricité (5 cours)
    {
        title: 'Changer un interrupteur simple',
        slug: 'changer-un-interrupteur-simple',
        littleSummary: 'Apprenez à remplacer un interrupteur en toute sécurité.',
        summary:
            "Vous découvrirez comment couper le circuit, identifier les fils, retirer l'ancien interrupteur et poser un nouveau modèle sans risque électrique.",
        difficulty: 3,
        authorId: 5,
        categoryId: 3,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Installer une prise électrique',
        slug: 'installer-une-prise-electrique',
        littleSummary: 'Ajoutez une prise de courant en toute sécurité.',
        summary:
            'Ce cours explique comment percer le mur, tirer les câbles et monter une prise électrique conforme aux normes.',
        difficulty: 4,
        authorId: 5,
        categoryId: 3,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Changer un fusible',
        slug: 'changer-un-fusible',
        littleSummary: 'Remplacez un fusible grillé simplement.',
        summary:
            'Apprenez à identifier le fusible défaillant, le retirer et installer un nouveau fusible de la bonne intensité.',
        difficulty: 2,
        authorId: 5,
        categoryId: 3,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Changer une ampoule',
        slug: 'changer-une-ampoule',
        littleSummary: 'Remplacez une ampoule grillée en quelques secondes.',
        summary:
            "Ce tutoriel rapide montre comment dévisser l'ancienne ampoule et visser la nouvelle, en respectant les types d'ampoules.",
        difficulty: 1,
        authorId: 5,
        categoryId: 3,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Installer un détecteur de fumée',
        slug: 'installer-un-detecteur-de-fumee',
        littleSummary: 'Protégez votre maison avec un détecteur de fumée.',
        summary:
            'Découvrez comment choisir et installer un détecteur de fumée au plafond, en le reliant au circuit électrique si nécessaire.',
        difficulty: 2,
        authorId: 5,
        categoryId: 3,
        numberPage: 4,
        visibility: true,
    },
    // Chauffage (5 cours)
    {
        title: 'Purger un radiateur à eau',
        slug: 'purger-un-radiateur-a-eau',
        littleSummary: 'Nettoyez vos radiateurs pour améliorer la chaleur et réduire le bruit.',
        summary:
            'Ce cours montre la procédure complète pour purger un radiateur à eau, vérifier la pression et rétablir un rendement optimal de votre chauffage central.',
        difficulty: 2,
        authorId: 8,
        categoryId: 4,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Changer un radiateur',
        slug: 'changer-un-radiateur',
        littleSummary: 'Remplacez un vieux radiateur par un modèle moderne.',
        summary:
            "Apprenez à vidanger le circuit, démonter l'ancien radiateur et installer le nouveau, en purgeant et testant le système.",
        difficulty: 4,
        authorId: 8,
        categoryId: 4,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Nettoyer un conduit de cheminée',
        slug: 'nettoyer-un-conduit-de-cheminee',
        littleSummary: "Assurez la sécurité et l'efficacité de votre cheminée.",
        summary:
            "Ce cours explique comment nettoyer les dépôts de suie dans un conduit de cheminée pour éviter les risques d'incendie.",
        difficulty: 3,
        authorId: 8,
        categoryId: 4,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Installer un thermostat programmable',
        slug: 'installer-un-thermostat-programmable',
        littleSummary: 'Contrôlez votre chauffage intelligemment.',
        summary:
            "Découvrez comment remplacer votre thermostat ancien par un modèle programmable pour économiser de l'énergie.",
        difficulty: 3,
        authorId: 8,
        categoryId: 4,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Isoler un mur intérieur',
        slug: 'isoler-un-mur-interieur',
        littleSummary: "Améliorez l'isolation thermique de votre maison.",
        summary:
            "Ce tutoriel montre comment poser de l'isolant sur un mur intérieur pour réduire les pertes de chaleur.",
        difficulty: 3,
        authorId: 8,
        categoryId: 4,
        numberPage: 4,
        visibility: true,
    },
    // Carrelage (5 cours)
    {
        title: 'Poser une faïence murale',
        slug: 'poser-une-faience-murale',
        littleSummary: 'Posez une faïence propre et régulière dans votre salle de bain ou cuisine.',
        summary:
            'Ce cours de carrelage vous accompagne de la préparation du mur à la réalisation des joints, avec les bons gestes pour un mur esthétique et durable.',
        difficulty: 4,
        authorId: 8,
        categoryId: 5,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Poser du carrelage au sol',
        slug: 'poser-du-carrelage-au-sol',
        littleSummary: 'Installez un carrelage résistant sur votre sol.',
        summary:
            'Apprenez à préparer le sol, étaler le mortier et poser les carreaux avec des joints réguliers pour un sol durable.',
        difficulty: 4,
        authorId: 8,
        categoryId: 5,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Réparer une fissure dans le carrelage',
        slug: 'reparer-une-fissure-dans-le-carrelage',
        littleSummary: 'Réparez une fissure sans remplacer le carreau.',
        summary:
            'Ce cours montre comment reboucher une fissure dans un carreau de carrelage avec du mastic adapté.',
        difficulty: 2,
        authorId: 8,
        categoryId: 5,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Poser une moquette',
        slug: 'poser-une-moquette',
        littleSummary: 'Installez une moquette douce et isolante.',
        summary:
            'Découvrez comment préparer le sol, couper la moquette et la fixer pour un revêtement de sol confortable.',
        difficulty: 3,
        authorId: 8,
        categoryId: 5,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Changer un carreau de carrelage',
        slug: 'changer-un-carreau-de-carrelage',
        littleSummary: 'Remplacez un carreau cassé facilement.',
        summary:
            "Apprenez à retirer l'ancien carreau, préparer la surface et poser un nouveau carreau avec des joints invisibles.",
        difficulty: 3,
        authorId: 8,
        categoryId: 5,
        numberPage: 4,
        visibility: true,
    },
    // Peinture (5 cours)
    {
        title: 'Préparer et peindre un mur',
        slug: 'preparer-et-peindre-un-mur',
        littleSummary: 'Préparation du support, sous-couche et application de la peinture.',
        summary:
            'Dans ce cours de peinture, vous apprendrez à préparer un mur abîmé, appliquer une sous-couche et finir proprement avec un rouleau et un pinceau.',
        difficulty: 2,
        authorId: 4,
        categoryId: 6,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Poser du papier peint',
        slug: 'poser-du-papier-peint',
        littleSummary: 'Habillez vos murs avec du papier peint.',
        summary:
            'Ce tutoriel explique comment préparer le mur, couper le papier et le coller pour un résultat sans bulles.',
        difficulty: 3,
        authorId: 4,
        categoryId: 6,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Peindre une porte',
        slug: 'peindre-une-porte',
        littleSummary: 'Redonnez vie à une porte avec de la peinture.',
        summary:
            'Apprenez à poncer, masquer et peindre une porte en bois pour un fini lisse et durable.',
        difficulty: 2,
        authorId: 4,
        categoryId: 6,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Appliquer une peinture décorative',
        slug: 'appliquer-une-peinture-decorative',
        littleSummary: 'Créez des effets décoratifs sur vos murs.',
        summary:
            'Découvrez les techniques pour appliquer des peintures texturées ou à effets pour personnaliser vos intérieurs.',
        difficulty: 4,
        authorId: 4,
        categoryId: 6,
        numberPage: 4,
        visibility: true,
    },
    {
        title: 'Peindre un plafond',
        slug: 'peindre-un-plafond',
        littleSummary: 'Rafraîchissez votre plafond sans taches.',
        summary:
            'Ce cours montre comment préparer et peindre un plafond avec un rouleau adapté pour éviter les coulures.',
        difficulty: 3,
        authorId: 4,
        categoryId: 6,
        numberPage: 4,
        visibility: true,
    },
];
