import type { Prisma } from '../../../prisma/generated';

export const coursHasLearningObjectiveData: Prisma.CoursHasLearningObjectiveCreateManyInput[] = [
    // Menuiserie
    { coursId: 1, learningObjectiveId: 5 },
    { coursId: 1, learningObjectiveId: 6 },
    { coursId: 1, learningObjectiveId: 7 },
    { coursId: 2, learningObjectiveId: 13 },
    { coursId: 2, learningObjectiveId: 6 },
    { coursId: 3, learningObjectiveId: 20 },
    { coursId: 3, learningObjectiveId: 14 },
    { coursId: 4, learningObjectiveId: 19 },
    { coursId: 4, learningObjectiveId: 6 },
    { coursId: 5, learningObjectiveId: 13 },
    { coursId: 5, learningObjectiveId: 14 },
    // Plomberie
    { coursId: 6, learningObjectiveId: 1 },
    { coursId: 6, learningObjectiveId: 2 },
    { coursId: 6, learningObjectiveId: 3 },
    { coursId: 6, learningObjectiveId: 4 },
    { coursId: 7, learningObjectiveId: 16 },
    { coursId: 7, learningObjectiveId: 4 },
    { coursId: 8, learningObjectiveId: 21 },
    { coursId: 8, learningObjectiveId: 3 },
    { coursId: 9, learningObjectiveId: 2 },
    { coursId: 9, learningObjectiveId: 3 },
    { coursId: 9, learningObjectiveId: 4 },
    { coursId: 10, learningObjectiveId: 26 },
    { coursId: 10, learningObjectiveId: 3 },
    // Electricité
    { coursId: 11, learningObjectiveId: 7 },
    { coursId: 11, learningObjectiveId: 8 },
    { coursId: 12, learningObjectiveId: 15 },
    { coursId: 12, learningObjectiveId: 7 },
    { coursId: 13, learningObjectiveId: 22 },
    { coursId: 13, learningObjectiveId: 7 },
    { coursId: 14, learningObjectiveId: 27 },
    { coursId: 14, learningObjectiveId: 7 },
    { coursId: 15, learningObjectiveId: 7 },
    { coursId: 15, learningObjectiveId: 8 },
    // Chauffage
    { coursId: 16, learningObjectiveId: 9 },
    { coursId: 16, learningObjectiveId: 4 },
    { coursId: 17, learningObjectiveId: 17 },
    { coursId: 17, learningObjectiveId: 9 },
    { coursId: 18, learningObjectiveId: 28 },
    { coursId: 18, learningObjectiveId: 9 },
    { coursId: 19, learningObjectiveId: 7 },
    { coursId: 19, learningObjectiveId: 8 },
    { coursId: 20, learningObjectiveId: 23 },
    { coursId: 20, learningObjectiveId: 10 },
    // Carrelage
    { coursId: 21, learningObjectiveId: 11 },
    { coursId: 21, learningObjectiveId: 12 },
    { coursId: 22, learningObjectiveId: 11 },
    { coursId: 22, learningObjectiveId: 12 },
    { coursId: 23, learningObjectiveId: 12 },
    { coursId: 23, learningObjectiveId: 6 },
    { coursId: 24, learningObjectiveId: 29 },
    { coursId: 24, learningObjectiveId: 6 },
    { coursId: 25, learningObjectiveId: 12 },
    { coursId: 25, learningObjectiveId: 6 },
    // Peinture
    { coursId: 26, learningObjectiveId: 10 },
    { coursId: 26, learningObjectiveId: 18 },
    { coursId: 27, learningObjectiveId: 24 },
    { coursId: 27, learningObjectiveId: 10 },
    { coursId: 28, learningObjectiveId: 18 },
    { coursId: 28, learningObjectiveId: 10 },
    { coursId: 29, learningObjectiveId: 18 },
    { coursId: 29, learningObjectiveId: 10 },
    { coursId: 30, learningObjectiveId: 18 },
    { coursId: 30, learningObjectiveId: 10 },
];
