import type { Prisma } from '../../../prisma/generated';

export const learningObjectivesData: Prisma.LearningObjectiveCreateManyInput[] = [
    { title: "Couper l'arrivée d'eau en sécurité" },
    { title: "Démonter l'ancien robinet" },
    { title: 'Raccorder les flexibles' },
    { title: 'Tester et contrôler les fuites' },
    { title: 'Mesurer et tracer une étagère droite' },
    { title: 'Choisir la bonne visserie pour le bois' },
    { title: "Vérifier l'isolement d'un fil électrique" },
    { title: 'Changer un interrupteur sans danger' },
    { title: 'Purger un radiateur efficacement' },
    { title: 'Préparer un mur avant peinture' },
    { title: 'Appliquer un mortier-colle régulier' },
    { title: 'Poser une première rangée de carrelage' },
    { title: 'Assembler des planches de bois' },
    { title: 'Finition et ponçage du bois' },
    { title: 'Installer une prise électrique' },
    { title: "Réparer une fuite d'eau" },
    { title: 'Changer un radiateur' },
    { title: 'Appliquer une couche de peinture' },
    { title: 'Poser du parquet flottant' },
    { title: 'Réparer une porte qui grince' },
    { title: 'Installer un WC suspendu' },
    { title: 'Changer un fusible' },
    { title: 'Isoler un mur' },
    { title: 'Poser du papier peint' },
    { title: 'Réparer une fuite de toit' },
    { title: 'Installer une douche' },
    { title: 'Changer une ampoule' },
    { title: 'Nettoyer un conduit de cheminée' },
    { title: 'Poser une moquette' },
    { title: 'Réparer une serrure' },
    { title: 'Installer un lave-linge' },
];
