import type { Prisma } from '../../../prisma/generated';

export const opinionsData: Prisma.OpinionCreateManyInput[] = [
    {
        userId: 2,
        coursId: 1,
        note: 5,
        content: "Très pratique, j'ai posé mon étagère sans problème.",
    },
    { userId: 3, coursId: 2, note: 4, content: 'Facile à suivre pour un kit.' },
    { userId: 6, coursId: 3, note: 5, content: 'La porte ne grince plus !' },
    { userId: 7, coursId: 4, note: 4, content: 'Parquet posé en une journée.' },
    { userId: 9, coursId: 5, note: 5, content: 'Boîte parfaite pour mes outils.' },
    { userId: 2, coursId: 6, note: 4, content: 'Siphon changé sans fuite.' },
    { userId: 3, coursId: 7, note: 5, content: 'Fuite réparée rapidement.' },
    { userId: 6, coursId: 8, note: 4, content: 'WC suspendu installé proprement.' },
    { userId: 7, coursId: 9, note: 5, content: 'Douche neuve fonctionnelle.' },
    { userId: 9, coursId: 10, note: 4, content: 'Douche complète réussie.' },
    { userId: 2, coursId: 11, note: 5, content: 'Interrupteur changé en sécurité.' },
    { userId: 3, coursId: 12, note: 4, content: 'Prise ajoutée facilement.' },
    { userId: 6, coursId: 13, note: 5, content: 'Fusible remplacé vite.' },
    { userId: 7, coursId: 14, note: 5, content: 'Ampoule changée en 1 min.' },
    { userId: 9, coursId: 15, note: 4, content: 'Détecteur installé et testé.' },
    { userId: 2, coursId: 16, note: 5, content: 'Radiateur plus chaud après purge.' },
    { userId: 3, coursId: 17, note: 4, content: 'Radiateur changé sans problème.' },
    { userId: 6, coursId: 18, note: 5, content: 'Cheminée propre et sûre.' },
    { userId: 7, coursId: 19, note: 4, content: 'Thermostat programmable utile.' },
    { userId: 9, coursId: 20, note: 5, content: "Mur isolé, économies d'énergie." },
    { userId: 2, coursId: 21, note: 4, content: 'Faïence posée régulièrement.' },
    { userId: 3, coursId: 22, note: 5, content: 'Sol carrelé impeccable.' },
    { userId: 6, coursId: 23, note: 5, content: 'Fissure réparée invisible.' },
    { userId: 7, coursId: 24, note: 4, content: 'Moquette posée confortablement.' },
    { userId: 9, coursId: 25, note: 5, content: 'Carreau changé parfaitement.' },
    { userId: 2, coursId: 26, note: 4, content: 'Mur peint sans traces.' },
    { userId: 3, coursId: 27, note: 5, content: 'Papier peint posé sans bulles.' },
    { userId: 6, coursId: 28, note: 4, content: 'Porte repeinte joliment.' },
    { userId: 7, coursId: 29, note: 5, content: 'Peinture décorative réussie.' },
    { userId: 9, coursId: 30, note: 4, content: 'Plafond peint proprement.' },
];
