import type { Prisma } from '../../../prisma/generated';

export const toolsData: Prisma.ToolCreateManyInput[] = [
    { name: 'Clé à molette', description: 'Pour serrer ou desserrer raccords et écrous.' },
    { name: 'Téflon', description: "Ruban d'étanchéité pour filetages de plomberie." },
    { name: 'Flexibles', description: "Tuyaux souples pour raccordement d'eau." },
    { name: 'Coupelle', description: 'Pièce de raccordement pour siphon.' },
    { name: 'Tournevis plat', description: 'Outil de base pour vis et interrupteurs.' },
    {
        name: 'Tournevis cruciforme',
        description: 'Indispensable pour fixations et mécanismes.',
    },
    { name: 'Niveau à bulle', description: "Permet d'aligner les éléments horizontaux." },
    { name: 'Mètre ruban', description: 'Précision de mesure pour découpe et pose.' },
    { name: 'Spatule crantée', description: 'Pour étaler le mortier-colle uniformément.' },
    { name: 'Rouleau de peinture', description: 'Pour appliquer la peinture rapidement.' },
    { name: 'Pince coupante', description: 'Pour couper câbles et gaines.' },
    {
        name: 'Pistolet à mastic',
        description: 'Pour joints étanches autour des installations.',
    },
    { name: 'Scie à bois', description: 'Pour couper le bois avec précision.' },
    { name: 'Marteau', description: 'Outil essentiel pour clouer et assembler.' },
    { name: 'Perceuse', description: 'Pour percer des trous dans le bois ou le mur.' },
    { name: 'Ponceuse', description: 'Pour lisser les surfaces en bois.' },
    { name: 'Multimètre', description: "Pour mesurer la tension et l'intensité." },
    { name: 'Pince à dénuder', description: "Pour retirer l'isolant des fils." },
    { name: 'Clé anglaise', description: 'Pour serrer les écrous de plomberie.' },
    { name: "Tuyau d'arrosage", description: "Pour tester les installations d'eau." },
    { name: 'Brosse à radiateur', description: 'Pour nettoyer les radiateurs.' },
    { name: 'Papier de verre', description: 'Pour poncer les surfaces.' },
    { name: 'Cutter', description: 'Pour couper les matériaux souples.' },
    { name: 'Échelle', description: 'Pour accéder aux hauteurs.' },
    { name: 'Gants de protection', description: 'Pour se protéger les mains.' },
    { name: 'Lunettes de sécurité', description: 'Pour protéger les yeux.' },
    { name: 'Masque', description: "Pour éviter l'inhalation de poussières." },
    { name: 'Bande adhésive', description: 'Pour fixer temporairement.' },
    { name: 'Colle à bois', description: 'Pour assembler les pièces de bois.' },
    { name: 'Vernis', description: 'Pour protéger et finir le bois.' },
];
