import argon2 from 'argon2';
import type { Prisma } from '../../../prisma/generated';

export const usersData: Prisma.UserCreateManyInput[] = [
    {
        email: 'test@test.test',
        firstname: 'Test',
        lastname: 'Admin',
        pseudo: 'admin',
        password: await argon2.hash('test'),
        roleId: 3,
        verified: true,
    },
    {
        email: 'samed@celik.oclock',
        firstname: 'Samed',
        lastname: 'Celik',
        pseudo: 'TheKingOfLyon',
        password: await argon2.hash('samed'),
        roleId: 1,
        verified: true,
    },
    {
        email: 'jacques@duchamplecheval.oclock',
        firstname: 'Jacques',
        lastname: 'Cheval',
        pseudo: 'President',
        password: await argon2.hash('jacques'),
        roleId: 1,
        verified: true,
    },
    {
        email: 'loic@leger.oclock',
        firstname: 'Loic',
        lastname: 'Leger',
        pseudo: 'GifMaster',
        password: await argon2.hash('loic'),
        roleId: 2,
        verified: true,
    },
    {
        email: 'adrien@poncet.oclock',
        firstname: 'Adrien',
        lastname: 'Poncet',
        pseudo: 'DreadMaster',
        password: await argon2.hash('adrien'),
        roleId: 2,
        verified: true,
    },
    {
        email: 'maria@artisan.oclock',
        firstname: 'Maria',
        lastname: 'Artisan',
        pseudo: 'MariaDIY',
        password: await argon2.hash('maria'),
        roleId: 1,
        verified: true,
    },
    {
        email: 'nina@atelier.oclock',
        firstname: 'Nina',
        lastname: 'Atelier',
        pseudo: 'NinaNail',
        password: await argon2.hash('nina'),
        roleId: 1,
        verified: true,
    },
    {
        email: 'marc@bricoleur.oclock',
        firstname: 'Marc',
        lastname: 'Bricoleur',
        pseudo: 'MarcPro',
        password: await argon2.hash('marc'),
        roleId: 2,
        verified: true,
    },
    {
        email: 'alice@brico.oclock',
        firstname: 'Alice',
        lastname: 'Brico',
        pseudo: 'AliceFix',
        password: await argon2.hash('alice'),
        roleId: 1,
        verified: true,
    },
    {
        email: 'bob@maker.oclock',
        firstname: 'Bob',
        lastname: 'Maker',
        pseudo: 'BobMaker',
        password: await argon2.hash('bob'),
        roleId: 1,
        verified: true,
    },
];
